#!/bin/sh

set -e

export HGDIR=$(dirname $PWD)/mercurial
if [ ! -d "$HGDIR" ] ; then
  echo "Directory $HGDIR should have the Mercurial repository code"
  echo "Clone Mercurial from by running:"
  echo "    hg clone https://www.mercurial-scm.org/repo/hg $HGDIR"
  exit 1
fi
mkdir -p logs

HGRCPATH=$PWD/logs/.hgrc
export HGRCPATH

cat <<EOF >$HGRCPATH
[extensions]
perfarce=$PWD/perfarce.py
EOF

OLDPATH=$PATH
STAT=

# No longer compatible with versions of Mercurial prior to 4.5

for R in 4.5 4.5.1 4.5.2 4.5.3 ; do
   echo Building Mercurial $R
   ( cd $HGDIR ; hg up --clean $R ; make clean ; make local ) >logs/$R 2>&1
   PATH=$HGDIR:$PATH
   if hg help perfarce | grep "pull from Perforce" ; then
      echo Running
      if ./test-push-perforce "$@" >>logs/$R 2>&1 ; then
         RES=OK
      else
         RES="FAIL,RC=$?"
      fi
   else
      RES=NOLOAD
   fi
   echo "$R:$RES"
   STAT="$STAT $R:$RES"

   PATH=$OLDPATH
done
echo Results: $STAT

