#!/bin/sh

set -e

export HGDIR=$(dirname $PWD)/mercurial
if [ ! -d "$HGDIR" ] ; then
  echo "Directory $HGDIR should have the Mercurial repository code"
  echo "Clone Mercurial from by running:"
  echo "    hg clone https://www.mercurial-scm.org/repo/hg $HGDIR"
  exit 1
fi
mkdir -p logs

STAT=

# No longer compatible with versions of Mercurial prior to 4.5

for R in 4.5 4.5.1 4.5.2 4.5.3 \
         4.6 4.6.1 4.6.2 \
         4.7 4.7.1 4.7.2 \
         4.8 4.8.1 4.8.2 \
         4.9 4.9.1 \
         5.0 5.0.1 5.0.2 \
         5.1 5.1.1 5.1.2 \
         5.2 5.2.1 5.2.2 \
         5.3 5.3.1 5.3.2 \
         5.4 5.4.1 5.4.2 \
         5.5 5.5.1 5.5.2 \
         5.6 5.6.1 \
         5.7 5.7.1 \
         5.8 5.8.1 \
         5.9 5.9.1 5.9.2 5.9.3 \
         6.0 6.0.1 6.0.2 6.0.3 \
         6.1 6.1.1 6.1.2 6.1.3 6.1.4 \
         6.2 6.2.1 6.2.2 6.2.3 \
         6.3 6.3.1 6.3.2 6.3.3 \
         6.4 6.4.1 6.4.2 6.4.3 6.4.4 6.4.5 \
         6.5 6.5.1 6.5.2 ; do
   echo Building Mercurial $R
   if ! ( cd $HGDIR ; hg up --clean $R && make clean && make local ) >logs/$R 2>&1; then
      echo "Unable to build mercurial"
      echo "Check logs/$R for details"
      exit 1
   fi
   OLDPATH=$PATH
   PATH=$HGDIR:$PATH
   export HGRCPATH=$CUSTOM_HGRCPATH
   if hg --config extensions.perfarce=$PWD/perfarce.py help perfarce | grep "pull from Perforce" ; then
      echo Running
      if ./test-push-perforce "$@" >>logs/$R 2>&1 ; then
         RES=OK
      else
         RES="FAIL,RC=$?"
      fi
   else
      RES=NOLOAD
   fi
   echo "$R:$RES"
   STAT="$STAT $R:$RES"

   PATH=$OLDPATH
   export HGRCPATH=$OLDHGRCPATH
done
echo Results: $STAT

